{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tets_uid.serviceAccountName" . }}
  labels:
{{ include "tets_uid.labels" . | indent 4 }}
{{- end -}}
